-- ═══════════════════════════════════════════════════════════════
--  AUTOMATA schema v2 — nuevas columnas y tabla LAYER_STATS
--  Ejecutar contra AGP_Ingenieria con usuario DevIngenieria
-- ═══════════════════════════════════════════════════════════════

-- Columnas nuevas en PLANOS
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('[AUTOMATA].[PLANOS]') AND name='PERIMETRO_AREA')
    ALTER TABLE [AUTOMATA].[PLANOS] ADD PERIMETRO_AREA FLOAT NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('[AUTOMATA].[PLANOS]') AND name='PERIMETRO_LONG')
    ALTER TABLE [AUTOMATA].[PLANOS] ADD PERIMETRO_LONG FLOAT NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('[AUTOMATA].[PLANOS]') AND name='PERIMETRO_VERTICES')
    ALTER TABLE [AUTOMATA].[PLANOS] ADD PERIMETRO_VERTICES INT NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('[AUTOMATA].[PLANOS]') AND name='ANGULO_INSTALACION')
    ALTER TABLE [AUTOMATA].[PLANOS] ADD ANGULO_INSTALACION FLOAT NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('[AUTOMATA].[PLANOS]') AND name='TOTAL_LAYERS')
    ALTER TABLE [AUTOMATA].[PLANOS] ADD TOTAL_LAYERS INT NULL;

-- Tabla de stats por layer
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id=OBJECT_ID('[AUTOMATA].[LAYER_STATS]'))
BEGIN
    CREATE TABLE [AUTOMATA].[LAYER_STATS] (
        ID            INT IDENTITY(1,1) PRIMARY KEY,
        PLANO_ID      INT NOT NULL,
        LAYER_NAME    NVARCHAR(100) NOT NULL,
        ENTIDADES     INT NOT NULL DEFAULT 0,
        LONGITUD_TOTAL FLOAT NULL,
        CONSTRAINT FK_LAYERSTATS_PLANO FOREIGN KEY (PLANO_ID)
            REFERENCES [AUTOMATA].[PLANOS](ID) ON DELETE CASCADE
    );
    CREATE INDEX IX_LAYERSTATS_PLANO ON [AUTOMATA].[LAYER_STATS](PLANO_ID);
END
